config.clientSpawn = true
config.clientSpawnForced = {
    ['paredao'] = true
}

config.taxSafe = 0.01
config.taxDetained = 0.01
config.taxIPVA = 0.01
config.ipvaDays = 7

config.vehicles = {
    ------------------------------------------------------------------------------------------------------------------------
    -- CARS
    ------------------------------------------------------------------------------------------------------------------------
    ['asbo'] = { name = 'Asbo', maker = 'Maxwell', price = 100000, trunk = 50, glove = 15, type = 'car', class = 'compacts', banned = false },
    ['drafter'] = { name = 'Drafter', maker = 'Obey', price = 150000, trunk = 30, glove = 15, type  = 'car', class = 'sports', banned = false },
    ['emerus'] = { name = 'Emerus', maker = 'Progen', price = 300000, trunk = 20, glove = 15, type = 'car', class = 'sports', banned = false },
    ['glendale2'] = { name = 'Glendale 2', maker = 'Benefactor', price = 200000, trunk = 30, glove = 15, type = 'car', class = 'compacts', banned = false },
    ['remus'] = { name = 'Remus', maker = 'Annis', price = 150000, trunk = 30, glove = 15, type = 'car', class = 'compacts', banned = false },
    ['savestra'] = { name = 'Savestra', maker = 'Annis', price = 150000, trunk = 30, glove = 15, type = 'car', class = 'compacts', banned = false },
    ['entity3'] = { name = 'Entity 3', maker = 'MT', price = 400000, trunk = 20, glove = 15, type = 'car', class = 'sports', banned = false },
    ['rcbandito'] = { name = 'RC Bandito', maker = 'Rockstar', price = 1000000, trunk = 1000, glove = 15, type = 'rental', class = 'offroad', banned = false },
    ['kuruma'] = { name = 'Kuruma', maker = 'Karin', price = 375000, trunk = 50, glove = 15, type = 'car', class = 'sports', banned = false },
    ['sultan2'] = { name = 'Sultan 2', maker = 'Karin', price = 500000, trunk = 20, glove = 15, type = 'car', class = 'sports', banned = false },
    ['trophytruck2'] = { name = 'Trophytruck2', maker = 'Vapid', price = 400000, trunk = 20, glove = 15, type = 'car', class = 'offroad', banned = false },
    ['rhapsody'] = { name = 'Rhapsody', maker = 'Declasse', price = 10000, trunk = 30, glove = 15, type = 'car', class = 'compacts', banned = false },
    ['vacca'] = { name = 'Vacca', maker = 'Pegassi', price = 350000, trunk = 30, glove = 15, type = 'car', class = 'super', banned = false },
    ['pounder'] = { name = 'Pounder', maker = 'MTL', price = 1000000, trunk = 5000, glove = 15, type = 'car', class = 'commercial', banned = false },
    ['massacro'] = { name = 'Massacro', maker = 'Dewbauchee', price = 330000, trunk = 40, glove = 15, type = 'car', class = 'sports', banned = false },
    ['dominator7'] = { name = 'Dominator7', maker = 'Vapid', price = 355000, trunk = 30, glove = 15, type = 'car', class = 'muscle', banned = false },
    ['moonbeam'] = { name = 'Moonbeam', maker = 'Declasse', price = 220000, trunk = 150, glove = 15, type = 'car', class = 'muscle', banned = false },
    ['bfinjection'] = { name = 'Bfinjection', maker = 'Bf', price = 80000, trunk = 100, glove = 15, type = 'car', class = 'offroad', banned = false },
    ['entity2'] = { name = 'Entity2', maker = 'överflöd', price = 550000, trunk = 20, glove = 15, type = 'car', class = 'super', banned = false },
    ['deviant'] = { name = 'Deviant', maker = 'Schyster', price = 370000, trunk = 50, glove = 15, type = 'car', class = 'muscle', banned = false },
    ['pounder2'] = { name = 'Pounder2', maker = 'MTL', price = 1000000, trunk = 1200, glove = 15, type = 'car', class = 'commercial', banned = false },
    ['weevil'] = { name = 'weevil', maker = 'BF', price = 110000, trunk = 30, glove = 15, type = 'car', class = 'compacts', banned = false },
    ['granger'] = { name = 'Granger', maker = 'Declasse', price = 345000, trunk = 100, glove = 15, type = 'car', class = 'suvs', banned = false },
    ['buffalo'] = { name = 'Buffalo', maker = 'Bravado', price = 300000, trunk = 50, glove = 15, type = 'car', class = 'sports', banned = false },
    ['gresley'] = { name = 'Gresley', maker = 'Bravado', price = 150000, trunk = 50, glove = 15, type = 'car', class = 'suvs', banned = false },
    ['penetrator'] = { name = 'Penetrator', maker = 'Ocelot', price = 480000, trunk = 20, glove = 15, type = 'car', class = 'super', banned = false },
    ['faction3'] = { name = 'Faction3', maker = 'Willard', price = 350000, trunk = 60, glove = 15, type = 'car', class = 'muscle', banned = false },
    ['limo2'] = { name = 'limo2', maker = 'Benefactor', price = 400000, trunk = 30, glove = 15, type = 'car', class = 'sedans', banned = false },
    ['vstr'] = { name = 'vstr', maker = 'Albany', price = 400000, trunk = 30, glove = 15, type = 'car', class = 'Sports', banned = false },
    ['dominator3'] = { name = 'Dominator3', maker = 'Vapid', price = 305000, trunk = 30, glove = 15, type = 'car', class = 'muscle', banned = false },
    ['penumbra'] = { name = 'Penumbra', maker = 'Maibatsu', price = 150000, trunk = 40, glove = 15, type = 'car', class = 'sports', banned = false },
    ['blade'] = { name = 'Blade', maker = 'Vapid', price = 110000, trunk = 40, glove = 15, type = 'car', class = 'muscle', banned = false },
    ['raiden'] = { name = 'Raiden', maker = 'Coil', price = 240000, trunk = 50, glove = 15, type = 'car', class = 'sports', banned = false },
    ['baller3'] = { name = 'Baller3', maker = 'Gallivanter', price = 175000, trunk = 50, glove = 15, type = 'car', class = 'suvs', banned = false },
    ['monster4'] = { name = 'Monster', maker = 'Bravado', price = 1000000, trunk = 0, glove = 15, type = 'car', class = 'offroad', banned = false },
    ['hotring'] = { name = 'Hotring', maker = 'Declasse', price = 300000, trunk = 60, glove = 15, type = 'car', class = 'sports', banned = false },
    ['seminole'] = { name = 'Seminole', maker = 'Canis', price = 110000, trunk = 60, glove = 15, type = 'car', class = 'suvs', banned = false },
    ['btype3'] = { name = 'Btype3', maker = 'Albany', price = 100000, trunk = 40, glove = 15, type = 'car', class = 'sportsclassics', banned = false },
    ['tulip'] = { name = 'Tulip', maker = 'Declasse', price = 200000, trunk = 60, glove = 15, type = 'car', class = 'muscle', banned = false },
    ['windsor2'] = { name = 'Windsor2', maker = 'Enus', price = 200000, trunk = 40, glove = 15, type = 'car', class = 'coupes', banned = false },
    ['sugoi'] = { name = 'sugoi', maker = 'Dinka', price = 400000, trunk = 30, glove = 15, type = 'car', class = 'Sports', banned = false },
    ['kanjo'] = { name = 'Kanjo', maker = 'Dinka', price = 110000, trunk = 30, glove = 15, type = 'car', class = 'compacts', banned = false },
    ['italigtb'] = { name = 'Italigtb', maker = 'Progen', price = 600000, trunk = 20, glove = 15, type = 'car', class = 'super', banned = false },
    ['comet2'] = { name = 'Comet2', maker = 'Pfister', price = 250000, trunk = 40, glove = 15, type = 'car', class = 'sports', banned = false },
    ['emperor2'] = { name = 'Emperor 2', maker = 'Albany', price = 50000, trunk = 60, glove = 15, type = 'car', class = 'sedans', banned = false },
    ['krieger'] = { name = 'krieger', maker = 'Benefactor', price = 400000, trunk = 20, glove = 15, type = 'car', class = 'super', banned = false },
    ['dubsta2'] = { name = 'Dubsta2', maker = 'Benefactor', price = 240000, trunk = 200, glove = 15, type = 'car', class = 'suvs', banned = false },
    ['glendale'] = { name = 'Glendale', maker = 'Benefactor', price = 70000, trunk = 50, glove = 15, type = 'car', class = 'sedans', banned = false },
    ['autarch'] = { name = 'Autarch', maker = 'överflöd', price = 760000, trunk = 20, glove = 15, type = 'car', class = 'super', banned = false },
    ['ingot'] = { name = 'Ingot', maker = 'Vulcar', price = 160000, trunk = 60, glove = 15, type = 'car', class = 'sedans', banned = false },
    ['sentinel3'] = { name = 'Sentinel3', maker = 'Übermacht', price = 70000, trunk = 30, glove = 15, type = 'car', class = 'sports', banned = false },
    ['furoregt'] = { name = 'Furoregt', maker = 'Lampadati', price = 290000, trunk = 30, glove = 15, type = 'car', class = 'sports', banned = false },
    ['tyrant'] = { name = 'Tyrant', maker = 'överflöd', price = 650000, trunk = 30, glove = 15, type = 'car', class = 'super', banned = false },
    ['burrito3'] = { name = 'Burrito3', maker = 'Declasse', price = 260000, trunk = 120, glove = 15, type = 'car', class = 'vans', banned = false },
    ['riata'] = { name = 'Riata', maker = 'Vapid', price = 250000, trunk = 80, glove = 15, type = 'car', class = 'offroad', banned = false },
    ['imorgon'] = { name = 'imorgon', maker = 'Överflöd', price = 400000, trunk = 30, glove = 15, type = 'car', class = 'Sports', banned = false },
    ['adder'] = { name = 'Adder', maker = 'Truffade', price = 620000, trunk = 20, glove = 15, type = 'car', class = 'super', banned = false },
    ['zion2'] = { name = 'Zion2', maker = 'Übermacht', price = 60000, trunk = 40, glove = 15, type = 'car', class = 'coupes', banned = false },
    ['rapidgt2'] = { name = 'Rapidgt2', maker = 'Dewbauchee', price = 300000, trunk = 20, glove = 15, type = 'car', class = 'sports', banned = false },
    ['schafter4'] = { name = 'Schafter4', maker = 'Benefactor', price = 125000, trunk = 50, glove = 15, type = 'car', class = 'sports', banned = false },
    ['rumpo2'] = { name = 'Rumpo2', maker = 'Bravado', price = 260000, trunk = 120, glove = 15, type = 'car', class = 'vans', banned = true },
    ['paragon'] = { name = 'paragon', maker = 'Enus', price = 400000, trunk = 30, glove = 15, type = 'car', class = 'Sports', banned = false },
    ['comet5'] = { name = 'Comet5', maker = 'Pfister', price = 300000, trunk = 40, glove = 15, type = 'car', class = 'sports', banned = false },
    ['cavalcade2'] = { name = 'Cavalcade2', maker = 'Albany', price = 130000, trunk = 60, glove = 15, type = 'car', class = 'suvs', banned = false },
    ['zion'] = { name = 'Zion', maker = 'Übermacht', price = 50000, trunk = 50, glove = 15, type = 'car', class = 'coupes', banned = false },
    ['gauntlet3'] = { name = 'Gauntlet3', maker = 'Bravado', price = 195000, trunk = 40, glove = 15, type = 'car', class = 'muscle', banned = false },
    ['dloader'] = { name = 'Dloader', maker = 'Bravado', price = 150000, trunk = 80, glove = 15, type = 'car', class = 'offroad', banned = false },
    ['windsor'] = { name = 'Windsor', maker = 'Enus', price = 150000, trunk = 20, glove = 15, type = 'car', class = 'coupes', banned = false },
    ['pigalle'] = { name = 'Pigalle', maker = 'Lampadati', price = 250000, trunk = 60, glove = 15, type = 'car', class = 'sportsclassics', banned = false },
    ['bullet'] = { name = 'Bullet', maker = 'Vapid', price = 400000, trunk = 20, glove = 15, type = 'car', class = 'super', banned = false },
    ['asea'] = { name = 'Asea', maker = 'Declasse', price = 55000, trunk = 30, glove = 15, type = 'car', class = 'sedans', banned = false },
    ['brawler'] = { name = 'Brawler', maker = 'Coil', price = 250000, trunk = 50, glove = 15, type = 'car', class = 'offroad', banned = false },
    ['tailgater'] = { name = 'Tailgater', maker = 'Obey', price = 110000, trunk = 50, glove = 15, type = 'car', class = 'sedans', banned = false },
    ['rebla'] = { name = 'Rebla', maker = 'Übermacht', price = 500000, trunk = 50, glove = 15, type = 'car', class = 'suvs', banned = false },
    ['voodoo2'] = { name = 'Voodoo2', maker = 'Declasse', price = 220000, trunk = 100, glove = 15, type = 'car', class = 'muscle', banned = false },
    ['massacro2'] = { name = 'Massacro2', maker = 'Dewbauchee', price = 330000, trunk = 40, glove = 15, type = 'car', class = 'sports', banned = false },
    ['rapidgt'] = { name = 'Rapidgt', maker = 'Dewbauchee', price = 250000, trunk = 20, glove = 15, type = 'car', class = 'sports', banned = false },
    ['dubsta'] = { name = 'Dubsta', maker = 'Benefactor', price = 210000, trunk = 200, glove = 15, type = 'car', class = 'suvs', banned = false },
    ['deveste'] = { name = 'Deveste', maker = 'Principe', price = 1000000, trunk = 20, glove = 15, type = 'car', class = 'super', banned = false },
    ['fagaloa'] = { name = 'Fagaloa', maker = 'Vulcar', price = 320000, trunk = 80, glove = 15, type = 'car', class = 'sportsclassics', banned = false },
    ['dynasty'] = { name = 'Dynasty', maker = 'Weeny', price = 250000, trunk = 40, glove = 15, type = 'car', class = 'sportsclassics', banned = false },
    ['banshee'] = { name = 'Banshee', maker = 'Bravado', price = 300000, trunk = 30, glove = 15, type = 'car', class = 'sports', banned = false },
    ['habanero'] = { name = 'Habanero', maker = 'Emperor', price = 110000, trunk = 50, glove = 15, type = 'car', class = 'suvs', banned = false },
    ['futo2'] = { name = 'futo2', maker = 'Karin', price = 400000, trunk = 30, glove = 15, type = 'car', class = 'Sports', banned = false },
    ['radi'] = { name = 'Radi', maker = 'Vapid', price = 110000, trunk = 50, glove = 15, type = 'car', class = 'suvs', banned = false },
    ['blista3'] = { name = 'Blista3', maker = 'Dinka', price = 80000, trunk = 40, glove = 15, type = 'car', class = 'sports', banned = false },
    ['tampa'] = { name = 'Tampa', maker = 'Declasse', price = 170000, trunk = 100, glove = 15, type = 'car', class = 'muscle', banned = false },
    ['oracle2'] = { name = 'Oracle2', maker = 'Ubermacht', price = 80000, trunk = 60, glove = 15, type = 'car', class = 'coupes', banned = false },
    ['jester3'] = { name = 'Jester3', maker = 'Dinka', price = 345000, trunk = 30, glove = 15, type = 'car', class = 'sports', banned = false },
    ['bodhi2'] = { name = 'Bodhi2', maker = 'Canis', price = 170000, trunk = 90, glove = 15, type = 'car', class = 'offroad', banned = false },
    ['exemplar'] = { name = 'Exemplar', maker = 'Dewbauchee', price = 80000, trunk = 20, glove = 15, type = 'car', class = 'coupes', banned = false },
    ['schlagen'] = { name = 'Schlagen', maker = 'Benefactor', price = 690000, trunk = 30, glove = 15, type = 'car', class = 'sports', banned = false },
    ['nero2'] = { name = 'Nero2', maker = 'Truffade', price = 480000, trunk = 20, glove = 15, type = 'car', class = 'super', banned = false },
    ['jester4'] = { name = 'Jester4', maker = 'Dinka', price = 645000, trunk = 30, glove = 15, type = 'car', class = 'sports', banned = false },
    ['ellie'] = { name = 'Ellie', maker = 'Vapid', price = 320000, trunk = 50, glove = 15, type = 'car', class = 'muscle', banned = false },
    ['blista'] = { name = 'Blista', maker = 'Dinka', price = 17500, trunk = 40, glove = 15, type = 'car', class = 'compacts', banned = false },
    ['toreador'] = { name = 'toreador', maker = 'Pegassi', price = 400000, trunk = 30, glove = 15, type = 'car', class = 'sportsclassics', banned = false },
    ['rapidgt3'] = { name = 'Rapidgt3', maker = 'Dewbauchee', price = 200000, trunk = 40, glove = 15, type = 'car', class = 'sportsclassics', banned = false },
    ['impaler'] = { name = 'Impaler', maker = 'Declasse', price = 320000, trunk = 60, glove = 15, type = 'car', class = 'muscle', banned = false },
    ['sultan'] = { name = 'Sultan', maker = 'Karin', price = 210000, trunk = 50, glove = 15, type = 'car', class = 'sports', banned = false },
    ['sc1'] = { name = 'Sc1', maker = 'Übermacht', price = 495000, trunk = 20, glove = 15, type = 'car', class = 'super', banned = false },
    ['ruston'] = { name = 'Ruston', maker = 'Hijak', price = 370000, trunk = 20, glove = 15, type = 'car', class = 'sports', banned = false },
    ['lynx'] = { name = 'Lynx', maker = 'Ocelot', price = 370000, trunk = 30, glove = 15, type = 'car', class = 'sports', banned = false },
    ['bjxl'] = { name = 'Bjxl', maker = 'Karin', price = 110000, trunk = 50, glove = 15, type = 'car', class = 'suvs', banned = false },
    ['sentinel2'] = { name = 'Sentinel2', maker = 'Übermacht', price = 60000, trunk = 40, glove = 15, type = 'car', class = 'coupes', banned = false },
    ['bestiagts'] = { name = 'Bestiagts', maker = 'Grotti', price = 500000, trunk = 60, glove = 15, type = 'car', class = 'sports', banned = false },
    ['moonbeam2'] = { name = 'Moonbeam2', maker = 'Declasse', price = 250000, trunk = 70, glove = 15, type = 'car', class = 'muscle', banned = false },
    ['tropos'] = { name = 'Tropos', maker = 'Lampadati', price = 170000, trunk = 20, glove = 15, type = 'car', class = 'sports', banned = false },
    ['previon'] = { name = 'Previon', maker = 'Karin', price = 145000, trunk = 30, glove = 15, type = 'car', class = 'coupes', banned = false },
    ['retinue'] = { name = 'Retinue', maker = 'Vapid', price = 150000, trunk = 40, glove = 15, type = 'car', class = 'sportsclassics', banned = false },
    ['stratum'] = { name = 'Stratum', maker = 'Zirconium', price = 90000, trunk = 70, glove = 15, type = 'car', class = 'sedans', banned = false },
    ['gauntlet4'] = { name = 'Gauntlet4', maker = 'Bravado', price = 215000, trunk = 40, glove = 15, type = 'car', class = 'muscle', banned = false },
    ['baller'] = { name = 'Baller', maker = 'Gallivanter', price = 150000, trunk = 50, glove = 15, type = 'car', class = 'suvs', banned = false },
    ['khamelion'] = { name = 'Khamelion', maker = 'Hijak', price = 210000, trunk = 50, glove = 15, type = 'car', class = 'sports', banned = false },
    ['nebula'] = { name = 'Nebula', maker = 'Vulcar', price = 180000, trunk = 30, glove = 15, type = 'car', class = 'sportsclassics', banned = false },
    ['btype2'] = { name = 'Btype2', maker = 'Albany', price = 460000, trunk = 20, glove = 15, type = 'car', class = 'sportsclassics', banned = false },
    ['phoenix'] = { name = 'Phoenix', maker = 'Imponte', price = 250000, trunk = 40, glove = 15, type = 'car', class = 'muscle', banned = false },
    ['pony'] = { name = 'Pony', maker = 'Brute', price = 260000, trunk = 120, glove = 15, type = 'car', class = 'vans', banned = false },
    ['stalion2'] = { name = 'Stalion2', maker = 'Declasse', price = 150000, trunk = 100, glove = 15, type = 'car', class = 'muscle', banned = false },
    ['schwarzer'] = { name = 'Schwarzer', maker = 'Benefactor', price = 170000, trunk = 50, glove = 15, type = 'car', class = 'sports', banned = false },
    ['jugular'] = { name = 'Jugular', maker = 'Ocelot', price = 720000, trunk = 50, glove = 15, type = 'car', class = 'sports', banned = false },
    ['comet3'] = { name = 'Comet3', maker = 'Pfister', price = 290000, trunk = 40, glove = 15, type = 'car', class = 'sports', banned = false },
    ['club2'] = { name = 'Club2', maker = 'Bf', price = 60000, trunk = 25, glove = 15, type = 'car', class = 'compacts', banned = false },
    ['novak'] = { name = 'Novak', maker = 'Lampadati', price = 490000, trunk = 50, glove = 15, type = 'car', class = 'suvs', banned = false },
    ['virgo2'] = { name = 'Virgo2', maker = 'Dundreary', price = 250000, trunk = 100, glove = 15, type = 'car', class = 'muscle', banned = false },
    ['vagner'] = { name = 'Vagner', maker = 'Dewbauchee', price = 350000, trunk = 20, glove = 15, type = 'car', class = 'super', banned = false },
    ['baller6'] = { name = 'Baller6', maker = 'Gallivanter', price = 280000, trunk = 50, glove = 15, type = 'car', class = 'suvs', banned = false },
    ['oracle'] = { name = 'Oracle', maker = 'Ubermacht', price = 60000, trunk = 50, glove = 15, type = 'car', class = 'coupes', banned = false },
    ['virtue'] = { name = 'virtue', maker = 'Ocelot', price = 400000, trunk = 30, glove = 15, type = 'car', class = 'Super', banned = false },
    ['hotknife'] = { name = 'Hotknife', maker = 'Vapid', price = 180000, trunk = 30, glove = 15, type = 'car', class = 'muscle', banned = false },
    ['brioso'] = { name = 'Brioso', maker = 'Grotti', price = 25000, trunk = 30, glove = 15, type = 'car', class = 'compacts', banned = false },
    ['alpha'] = { name = 'Alpha', maker = 'Albany', price = 230000, trunk = 40, glove = 15, type = 'car', class = 'sports', banned = false },
    ['minivan'] = { name = 'Minivan', maker = 'Vapid', price = 110000, trunk = 70, glove = 15, type = 'car', class = 'vans', banned = false },
    ['surfer'] = { name = 'Surfer', maker = 'Bf', price = 150000, trunk = 80, glove = 15, type = 'car', class = 'vans', banned = false },
    ['brutus'] = { name = 'brutus', maker = 'Declasse', price = 110000, trunk = 50, glove = 15, type = 'car', class = 'muscle', banned = false },
    ['stinger'] = { name = 'Stinger', maker = 'Grotti', price = 220000, trunk = 20, glove = 15, type = 'car', class = 'sportsclassics', banned = false },
    ['sultan3'] = { name = 'sultan3', maker = 'Karin', price = 400000, trunk = 30, glove = 15, type = 'car', class = 'Sports', banned = false },
    ['prototipo'] = { name = 'Prototipo', maker = 'Grotti', price = 1000000, trunk = 20, glove = 15, type = 'car', class = 'super', banned = false },
    ['gauntlet'] = { name = 'Gauntlet', maker = 'Bravado', price = 165000, trunk = 40, glove = 15, type = 'car', class = 'muscle', banned = false },
    ['f620'] = { name = 'F620', maker = 'Ocelot', price = 55000, trunk = 30, glove = 15, type = 'car', class = 'coupes', banned = false },
    ['intruder'] = { name = 'Intruder', maker = 'Karin', price = 60000, trunk = 50, glove = 15, type = 'car', class = 'sedans', banned = false },
    ['chino'] = { name = 'Chino', maker = 'Vapid', price = 100000, trunk = 50, glove = 15, type = 'car', class = 'muscle', banned = false },
    ['cyclone'] = { name = 'Cyclone', maker = 'Coil', price = 920000, trunk = 20, glove = 15, type = 'car', class = 'super', banned = false },
    ['huntley'] = { name = 'Huntley', maker = 'Enus', price = 110000, trunk = 60, glove = 15, type = 'car', class = 'suvs', banned = false },
    ['pony2'] = { name = 'Pony2', maker = 'Brute', price = 260000, trunk = 120, glove = 15, type = 'car', class = 'vans', banned = false },
    ['pbus2'] = { name = 'Ônibus Festival', maker = 'Vapid', price = 1000000, trunk = 0, glove = 15, type = 'car', class = 'service', banned = false },
    ['lurcher'] = { name = 'Lurcher', maker = 'Albany', price = 150000, trunk = 60, glove = 15, type = 'car', class = 'muscle', banned = false },
    ['flashgt'] = { name = 'Flashgt', maker = 'Vapid', price = 370000, trunk = 30, glove = 15, type = 'car', class = 'sports', banned = false },
    ['jb700'] = { name = 'Jb700', maker = 'Dewbauchee', price = 220000, trunk = 30, glove = 15, type = 'car', class = 'sportsclassics', banned = false },
    ['italigto'] = { name = 'Italigto', maker = 'Grotti', price = 800000, trunk = 30, glove = 15, type = 'car', class = 'sports', banned = false },
    ['futo'] = { name = 'Futo', maker = 'Karin', price = 170000, trunk = 40, glove = 15, type = 'car', class = 'sports', banned = false },
    ['infernus2'] = { name = 'Infernus2', maker = 'Pegassi', price = 450000, trunk = 20, glove = 15, type = 'car', class = 'sportsclassics', banned = false },
    ['fusilade'] = { name = 'Fusilade', maker = 'Schyster', price = 210000, trunk = 40, glove = 15, type = 'car', class = 'sports', banned = false },
    ['sabregt2'] = { name = 'Sabregt2', maker = 'Declasse', price = 150000, trunk = 100, glove = 15, type = 'car', class = 'muscle', banned = false },
    ['baller2'] = { name = 'Baller2', maker = 'Gallivanter', price = 160000, trunk = 50, glove = 15, type = 'car', class = 'suvs', banned = false },
    ['cavalcade'] = { name = 'Cavalcade', maker = 'Albany', price = 110000, trunk = 60, glove = 15, type = 'car', class = 'suvs', banned = false },
    ['michelli'] = { name = 'Michelli', maker = 'Lampadati', price = 90000, trunk = 40, glove = 15, type = 'car', class = 'sportsclassics', banned = false },
    ['patriot2'] = { name = 'Patriot2', maker = 'Mammoth', price = 550000, trunk = 60, glove = 15, type = 'car', class = 'suvs', banned = false },
    ['virgo3'] = { name = 'Virgo3', maker = 'Dundreary', price = 180000, trunk = 100, glove = 15, type = 'car', class = 'muscle', banned = false },
    ['carbonizzare'] = { name = 'Carbonizzare', maker = 'Grotti', price = 290000, trunk = 30, glove = 15, type = 'car', class = 'sports', banned = false },
    ['cheburek'] = { name = 'Cheburek', maker = 'Rune', price = 170000, trunk = 50, glove = 15, type = 'car', class = 'sportsclassics', banned = false },
    ['everon'] = { name = 'Everon', maker = 'Karin', price = 700000, trunk = 250, glove = 15, type = 'car', class = 'offroad', banned = false },
    ['cypher'] = { name = 'Cypher', maker = 'Übermacht', price = 980000, trunk = 50, glove = 15, type = 'car', class = 'sports', banned = false },
    ['gauntlet2'] = { name = 'Gauntlet2', maker = 'Bravado', price = 165000, trunk = 40, glove = 15, type = 'car', class = 'muscle', banned = false },
    ['landstalker'] = { name = 'Landstalker', maker = 'Dundreary', price = 130000, trunk = 70, glove = 15, type = 'car', class = 'suvs', banned = false },
    ['streiter'] = { name = 'Streiter', maker = 'Benefactor', price = 250000, trunk = 70, glove = 15, type = 'car', class = 'sports', banned = false },
    ['coquette3'] = { name = 'Coquette3', maker = 'Invetero', price = 195000, trunk = 40, glove = 15, type = 'car', class = 'muscle', banned = false },
    ['stingergt'] = { name = 'Stingergt', maker = 'Grotti', price = 230000, trunk = 20, glove = 15, type = 'car', class = 'sportsclassics', banned = false },
    ['stalion'] = { name = 'Stalion', maker = 'Classique', price = 150000, trunk = 100, glove = 15, type = 'car', class = 'muscle', banned = false },
    ['omnis'] = { name = 'Omnis', maker = 'Obey', price = 240000, trunk = 20, glove = 15, type = 'car', class = 'sports', banned = false },
    ['sentinel'] = { name = 'Sentinel', maker = 'Übermacht', price = 50000, trunk = 50, glove = 15, type = 'car', class = 'coupes', banned = false },
    ['sultanrs'] = { name = 'Sultan RS', maker = 'Karin', price = 450000, trunk = 30, glove = 15, type = 'car', class = 'super', banned = false },
    ['kamacho'] = { name = 'Kamacho', maker = 'Canis', price = 350000, trunk = 200, glove = 15, type = 'car', class = 'offroad', banned = false },
    ['cheetah2'] = { name = 'Cheetah2', maker = 'Grotti', price = 240000, trunk = 20, glove = 15, type = 'car', class = 'sportsclassics', banned = false },
    ['menacer'] = { name = 'menacer', maker = 'HVY', price = 700000, trunk = 30, glove = 15, type = 'car', class = 'offroad', banned = false },
    ['deluxo'] = { name = 'deluxo', maker = 'Imponte', price = 400000, trunk = 20, glove = 15, type = 'car', class = 'sportsclassics', banned = false },
    ['voodoo'] = { name = 'Voodoo', maker = 'Declasse', price = 220000, trunk = 100, glove = 15, type = 'car', class = 'muscle', banned = false },
    ['elegy'] = { name = 'Elegy', maker = 'Annis', price = 350000, trunk = 30, glove = 15, type = 'car', class = 'sports', banned = false },
    ['speedo4'] = { name = 'speedo4', maker = 'Vapid', price = 220000, trunk = 100, glove = 15, type = 'car', class = 'vans', banned = false },
    ['youga3'] = { name = 'youga3', maker = 'Bravado', price = 220000, trunk = 100, glove = 15, type = 'car', class = 'vans', banned = false },
    ['vigilante'] = { name = 'vigilante', maker = 'Grotti', price = 400000, trunk = 0, glove = 15, type = 'car', class = 'super', banned = false },
    ['viseris'] = { name = 'viseris', maker = 'Lampadati', price = 400000, trunk = 30, glove = 15, type = 'car', class = 'sportsclassics', banned = false },
    ['stromberg'] = { name = 'stromberg', maker = 'Ocelot', price = 400000, trunk = 30, glove = 15, type = 'car', class = 'sportsclassics', banned = false },
    ['seminole2'] = { name = 'seminole2', maker = 'Canis', price = 400000, trunk = 50, glove = 15, type = 'car', class = 'suvs', banned = false },
    ['burrito2'] = { name = 'Burrito2', maker = 'Declasse', price = 500000, trunk = 120, glove = 15, type = 'car', class = 'vans', banned = false },
    ['coquette4'] = { name = 'coquette4', maker = 'Invetero', price = 400000, trunk = 30, glove = 15, type = 'car', class = 'Sports', banned = false },
    ['yosemite'] = { name = 'Yosemite', maker = 'Declasse', price = 350000, trunk = 100, glove = 15, type = 'car', class = 'muscle', banned = false },
    ['felon'] = { name = 'Felon', maker = 'Lampadati', price = 70000, trunk = 50, glove = 15, type = 'car', class = 'coupes', banned = false },
    ['sheava'] = { name = 'Sheava', maker = 'Emperor', price = 700000, trunk = 20, glove = 15, type = 'car', class = 'super', banned = false },
    ['turismor'] = { name = 'Turismor', maker = 'Grotti', price = 700000, trunk = 20, glove = 15, type = 'car', class = 'super', banned = false },
    ['visione'] = { name = 'Visione', maker = 'Grotti', price = 650000, trunk = 20, glove = 15, type = 'car', class = 'super', banned = false },
    ['virgo'] = { name = 'Virgo', maker = 'Albany', price = 150000, trunk = 100, glove = 15, type = 'car', class = 'muscle', banned = false },
    ['panto'] = { name = 'Panto', maker = 'Benefactor', price = 5000, trunk = 20, glove = 15, type = 'car', class = 'compacts', banned = false },
    ['rumpo'] = { name = 'Rumpo', maker = 'Bravado', price = 400000, trunk = 180, glove = 15, type = 'car', class = 'vans', banned = false },
    ['ruiner'] = { name = 'Ruiner', maker = 'Imponte', price = 150000, trunk = 100, glove = 15, type = 'car', class = 'muscle', banned = false },
    ['coquette'] = { name = 'Coquette', maker = 'Invetero', price = 250000, trunk = 30, glove = 15, type = 'car', class = 'sports', banned = false },
    ['zr350'] = { name = 'zr350', maker = 'Annis', price = 400000, trunk = 30, glove = 15, type = 'car', class = 'Sports', banned = false },
    ['phantom3'] = { name = 'Phantom', maker = 'Jobuilt', price = 1000000, trunk = 0, glove = 15, type = 'car', class = 'commercial', banned = false },
    ['rallytruck'] = { name = 'RallyTruck', maker = 'MTL', price = 2000000, trunk = 500, glove = 15, type = 'car', class = 'service', banned = false },
    ['dukes'] = { name = 'Dukes', maker = 'Imponte', price = 150000, trunk = 40, glove = 15, type = 'car', class = 'muscle', banned = false },
    ['picador'] = { name = 'Picador', maker = 'Cheval', price = 150000, trunk = 90, glove = 15, type = 'car', class = 'muscle', banned = false },
    ['slamvan3'] = { name = 'Slamvan3', maker = 'Vapid', price = 230000, trunk = 150, glove = 15, type = 'car', class = 'muscle', banned = false },
    ['mule2'] = { name = 'Mule2', maker = 'Maibatsu', price = 1000000, trunk = 400, glove = 15, type = 'car', class = 'commercial', banned = false },
    ['minivan2'] = { name = 'Minivan2', maker = 'Vapid', price = 220000, trunk = 60, glove = 15, type = 'car', class = 'vans', banned = false },
    ['growler'] = { name = 'growler', maker = 'Pfister', price = 400000, trunk = 30, glove = 15, type = 'car', class = 'Sports', banned = false },
    ['komoda'] = { name = 'komoda', maker = 'Lampadati', price = 400000, trunk = 30, glove = 15, type = 'car', class = 'Sports', banned = false },
    ['panthere'] = { name = 'panthere', maker = 'Toundra', price = 400000, trunk = 30, glove = 15, type = 'car', class = 'Sports', banned = false },
    ['paragon2'] = { name = 'paragon2', maker = 'Enus', price = 400000, trunk = 30, glove = 15, type = 'car', class = 'Sports', banned = false },
    ['casco'] = { name = 'Casco', maker = 'Lampadati', price = 355000, trunk = 50, glove = 15, type = 'car', class = 'sportsclassics', banned = false },
    ['patriot'] = { name = 'Patriot', maker = 'Mammoth', price = 250000, trunk = 70, glove = 15, type = 'car', class = 'suvs', banned = false },
    ['mesa3'] = { name = 'Mesa3', maker = 'Canis', price = 200000, trunk = 60, glove = 15, type = 'car', class = 'offroad', banned = false },
    ['yosemite3'] = { name = 'yosemite3', maker = 'Declasse', price = 400000, trunk = 50, glove = 15, type = 'car', class = 'suvs', banned = false },
    ['scramjet'] = { name = 'scramjet', maker = 'Declasse', price = 400000, trunk = 30, glove = 15, type = 'car', class = 'Super', banned = false },
    ['nightshade'] = { name = 'Nightshade', maker = 'Imponte', price = 270000, trunk = 30, glove = 15, type = 'car', class = 'muscle', banned = false },
    ['formula2'] = { name = 'formula2', maker = 'Ocelot', price = 400000, trunk = 0, glove = 0, type = 'car', class = 'Sports', banned = false },
    ['vapidlow'] = { name = 'vapidlow', maker = 'Vapid', price = 1000000, trunk = 0, glove = 15, type = 'car', class = 'offroad', banned = false },
    ['veto2'] = { name = 'Veto 2', maker = 'Dinka', price = 200000, trunk = 4, glove = 15, type = 'car', class = 'sports', banned = false },
    ['rumpo3'] = { name = 'Rumpo3', maker = 'Bravado', price = 350000, trunk = 120, glove = 15, type = 'car', class = 'vans', banned = false },
    ['verus'] = { name = 'Verus', maker = 'Dinka', price = 200000, trunk = 4, glove = 15, type = 'car', class = 'offroad', banned = false },
    ['pfister811'] = { name = 'Pfister811', maker = 'Pfister', price = 530000, trunk = 20, glove = 15, type = 'car', class = 'super', banned = false },
    ['feltzer3'] = { name = 'Feltzer3', maker = 'Benefactor', price = 300000, trunk = 40, glove = 15, type = 'car', class = 'sportsclassics', banned = false },
    ['buccaneer'] = { name = 'Buccaneer', maker = 'Albany', price = 130000, trunk = 50, glove = 15, type = 'car', class = 'muscle', banned = false },
    ['hermes'] = { name = 'Hermes', maker = 'Albany', price = 280000, trunk = 50, glove = 15, type = 'car', class = 'muscle', banned = false },
    ['guardian'] = { name = 'Guardian', maker = 'Vapid', price = 500000, trunk = 150, glove = 15, type = 'car', class = 'industrial', banned = false },
    ['dubsta3'] = { name = 'Dubsta3', maker = 'Benefactor', price = 300000, trunk = 200, glove = 15, type = 'car', class = 'offroad', banned = false },
    ['clique'] = { name = 'Clique', maker = 'Vapid', price = 360000, trunk = 40, glove = 15, type = 'car', class = 'muscle', banned = false },
    ['reaper'] = { name = 'Reaper', maker = 'Pegassi', price = 620000, trunk = 20, glove = 15, type = 'car', class = 'super', banned = false },
    ['buccaneer2'] = { name = 'Buccaneer2', maker = 'Albany', price = 250000, trunk = 60, glove = 15, type = 'car', class = 'muscle', banned = false },
    ['zorrusso'] = { name = 'zorrusso', maker = 'Pegassi', price = 400000, trunk = 20, glove = 15, type = 'car', class = 'super', banned = false },
    ['fmj'] = { name = 'Fmj', maker = 'Vapid', price = 520000, trunk = 20, glove = 15, type = 'car', class = 'super', banned = false },
    ['buffalo2'] = { name = 'Buffalo2', maker = 'Bravado', price = 300000, trunk = 50, glove = 15, type = 'car', class = 'sports', banned = false },
    ['z190'] = { name = 'Z190', maker = 'Karin', price = 350000, trunk = 40, glove = 15, type = 'car', class = 'sportsclassics', banned = false },
    ['schafter3'] = { name = 'Schafter3', maker = 'Benefactor', price = 275000, trunk = 50, glove = 15, type = 'car', class = 'sports', banned = false },
    ['jester'] = { name = 'Jester', maker = 'Dinka', price = 450000, trunk = 30, glove = 15, type = 'car', class = 'sports', banned = false },
    ['sandking'] = { name = 'Sandking', maker = 'Vapid', price = 300000, trunk = 120, glove = 15, type = 'car', class = 'offroad', banned = false },
    ['premier'] = { name = 'Premier', maker = 'Declasse', price = 35000, trunk = 50, glove = 15, type = 'car', class = 'sedans', banned = false },
    ['washington'] = { name = 'Washington', maker = 'Albany', price = 130000, trunk = 60, glove = 15, type = 'car', class = 'sedans', banned = false },
    ['cognoscenti'] = { name = 'Cognoscenti', maker = 'Enus', price = 280000, trunk = 50, glove = 15, type = 'car', class = 'sedans', banned = false },
    ['contender'] = { name = 'Contender', maker = 'Vapid', price = 500000, trunk = 80, glove = 15, type = 'car', class = 'suvs', banned = false },
    ['torero'] = { name = 'Torero', maker = 'Pegassi', price = 160000, trunk = 30, glove = 15, type = 'car', class = 'sportsclassics', banned = false },
    ['t20'] = { name = 'T20', maker = 'Progen', price = 670000, trunk = 20, glove = 15, type = 'car', class = 'super', banned = false },
    ['cogcabrio'] = { name = 'Cogcabrio', maker = 'Enus', price = 130000, trunk = 60, glove = 15, type = 'car', class = 'coupes', banned = false },
    ['openwheel1'] = { name = 'openwheel1', maker = 'Benefactor', price = 400000, trunk = 0, glove = 0, type = 'car', class = 'Sports', banned = false },
    ['formula'] = { name = 'formula', maker = 'Progen Dinka', price = 400000, trunk = 0, glove = 0, type = 'car', class = 'Sports', banned = false },
    ['neo'] = { name = 'neo', maker = 'Vysser', price = 400000, trunk = 30, glove = 15, type = 'car', class = 'Sports', banned = false },
    ['tailgater2'] = { name = 'tailgater2', maker = 'Obey', price = 400000, trunk = 30, glove = 15, type = 'car', class = 'sedans', banned = false },
    ['mamba'] = { name = 'Mamba', maker = 'Declasse', price = 300000, trunk = 50, glove = 15, type = 'car', class = 'sportsclassics', banned = false },
    ['italigtb2'] = { name = 'Italigtb2', maker = 'Progen', price = 610000, trunk = 20, glove = 15, type = 'car', class = 'super', banned = false },
    ['gp1'] = { name = 'Gp1', maker = 'Progen', price = 495000, trunk = 20, glove = 15, type = 'car', class = 'super', banned = false },
    ['cog552'] = { name = 'Cog552', maker = 'Enus', price = 400000, trunk = 50, glove = 15, type = 'car', class = 'sedans', banned = false },
    ['fugitive'] = { name = 'Fugitive', maker = 'Cheval', price = 50000, trunk = 50, glove = 15, type = 'car', class = 'sedans', banned = false },
    ['primo'] = { name = 'Primo', maker = 'Albany', price = 130000, trunk = 50, glove = 15, type = 'car', class = 'sedans', banned = false },
    ['infernus'] = { name = 'Infernus', maker = 'Pegassi', price = 470000, trunk = 20, glove = 15, type = 'car', class = 'super', banned = false },
    ['bobcatxl'] = { name = 'Bobcatxl', maker = 'Vapid', price = 260000, trunk = 100, glove = 15, type = 'car', class = 'vans', banned = false },
    ['bison'] = { name = 'Bison', maker = 'Bravado', price = 220000, trunk = 70, glove = 15, type = 'car', class = 'vans', banned = false },
    ['everon2'] = { name = 'everon2', maker = 'Karin', price = 400000, trunk = 200, glove = 15, type = 'car', class = 'Sports', banned = false },
    ['banshee2'] = { name = 'Banshee2', maker = 'Bravado', price = 370000, trunk = 20, glove = 15, type = 'car', class = 'super', banned = false },
    ['emperor'] = { name = 'Emperor', maker = 'Albany', price = 50000, trunk = 60, glove = 15, type = 'car', class = 'sedans', banned = false },
    ['verlierer2'] = { name = 'Verlierer2', maker = 'Bravado', price = 380000, trunk = 20, glove = 15, type = 'car', class = 'sports', banned = false },
    ['monroe'] = { name = 'Monroe', maker = 'Pegassi', price = 260000, trunk = 20, glove = 15, type = 'car', class = 'sportsclassics', banned = false },
    ['sadler'] = { name = 'Sadler', maker = 'Vapid', price = 180000, trunk = 200, glove = 15, type = 'car', class = 'utility', banned = false },
    ['ninef'] = { name = 'Ninef', maker = 'Obey', price = 290000, trunk = 40, glove = 15, type = 'car', class = 'sports', banned = false },
    ['sabregt'] = { name = 'Sabregt', maker = 'Declasse', price = 260000, trunk = 100, glove = 15, type = 'car', class = 'muscle', banned = false },
    ['raptor'] = { name = 'Raptor', maker = 'Bf', price = 300000, trunk = 20, glove = 15, type = 'car', class = 'sports', banned = false },
    ['kuruma2'] = { name = 'Kuruma Blindado', maker = 'Karin', price = 1000000, trunk = 90, glove = 15, type = 'car', class = 'sports', banned = false },
    ['xls'] = { name = 'Xls', maker = 'Benefactor', price = 300000, trunk = 50, glove = 15, type = 'car', class = 'suvs', banned = false },
    ['dominator'] = { name = 'Dominator', maker = 'Vapid', price = 250000, trunk = 50, glove = 15, type = 'car', class = 'muscle', banned = false },
    ['prairie'] = { name = 'Prairie', maker = 'Bollokan', price = 1000, trunk = 25, glove = 15, type = 'car', class = 'compacts', banned = false },
    ['mule3'] = { name = 'Mule3', maker = 'Maibatsu', price = 1500000, trunk = 700, glove = 15, type = 'car', class = 'commercial', banned = false },
    ['vigero'] = { name = 'Vigero', maker = 'Declasse', price = 170000, trunk = 100, glove = 15, type = 'car', class = 'muscle', banned = false },
    ['cognoscenti2'] = { name = 'Cognoscenti2', maker = 'Enus', price = 400000, trunk = 50, glove = 15, type = 'car', class = 'sedans', banned = false },
    ['brioso2'] = { name = 'Brioso2', maker = 'Grotti', price = 25000, trunk = 30, glove = 15, type = 'car', class = 'compacts', banned = false },
    ['rocoto'] = { name = 'Rocoto', maker = 'Obey', price = 110000, trunk = 60, glove = 15, type = 'car', class = 'suvs', banned = false },
    ['osiris'] = { name = 'Osiris', maker = 'Pegassi', price = 460000, trunk = 20, glove = 15, type = 'car', class = 'super', banned = false },
    ['surano'] = { name = 'Surano', maker = 'Benefactor', price = 310000, trunk = 30, glove = 15, type = 'car', class = 'sports', banned = false },
    ['zentorno'] = { name = 'Zentorno', maker = 'Pegassi', price = 920000, trunk = 20, glove = 15, type = 'car', class = 'super', banned = false },
    ['schafter5'] = { name = 'Schafter5', maker = 'Benefactor', price = 275000, trunk = 50, glove = 15, type = 'car', class = 'sedans', banned = false },
    ['youga'] = { name = 'Youga', maker = 'Bravado', price = 260000, trunk = 120, glove = 15, type = 'car', class = 'vans', banned = false },    
    ['tempesta'] = { name = 'Tempesta', maker = 'Pegassi', price = 600000, trunk = 20, glove = 15, type = 'car', class = 'super', banned = false },
    ['peyote'] = { name = 'Peyote', maker = 'Vapid', price = 150000, trunk = 50, glove = 15, type = 'car', class = 'sportsclassics', banned = false },
    ['faction'] = { name = 'Faction', maker = 'Willard', price = 150000, trunk = 50, glove = 15, type = 'car', class = 'muscle', banned = false },
    ['gauntlet5'] = { name = 'Gauntlet5', maker = 'Bravado', price = 245000, trunk = 40, glove = 15, type = 'car', class = 'muscle', banned = false },
    ['ztype'] = { name = 'Ztype', maker = 'Truffade', price = 400000, trunk = 20, glove = 15, type = 'car', class = 'sportsclassics', banned = false },
    ['italirsx'] = { name = 'italirsx', maker = 'Grotti', price = 400000, trunk = 30, glove = 15, type = 'car', class = 'Sports', banned = false },
    ['pariah'] = { name = 'Pariah', maker = 'Ocelot', price = 500000, trunk = 30, glove = 15, type = 'car', class = 'sports', banned = false },
    ['xls2'] = { name = 'Xls2', maker = 'Benefactor', price = 350000, trunk = 50, glove = 15, type = 'car', class = 'suvs', banned = false },
    ['blista2'] = { name = 'Blista2', maker = 'Dinka', price = 100000, trunk = 40, glove = 15, type = 'car', class = 'compacts', banned = false },
    ['trophytruck'] = { name = 'Trophytruck', maker = 'Vapid', price = 1000000, trunk = 20, glove = 15, type = 'car', class = 'offroad', banned = false },
    ['dilettante'] = { name = 'Dilettante', maker = 'Karin', price = 60000, trunk = 30, glove = 15, type = 'car', class = 'compacts', banned = false },
    ['vectre'] = { name = 'vectre', maker = 'Emperor', price = 400000, trunk = 30, glove = 15, type = 'car', class = 'Sports', banned = false },
    ['outlaw'] = { name = 'Outlaw', maker = 'Nagasaki', price = 500000, trunk = 40, glove = 15, type = 'car', class = 'offroad', banned = false },
    ['nightshark'] = { name = 'nightshark', maker = 'HVY', price = 700000, trunk = 30, glove = 15, type = 'car', class = 'offroad', banned = false },
    ['le7b'] = { name = 'Le7b', maker = 'Annis', price = 700000, trunk = 20, glove = 15, type = 'car', class = 'super', banned = false },
    ['swinger'] = { name = 'Swinger', maker = 'Ocelot', price = 250000, trunk = 20, glove = 15, type = 'car', class = 'sportsclassics', banned = false },
    ['gb200'] = { name = 'Gb200', maker = 'Vapid', price = 195000, trunk = 20, glove = 15, type = 'car', class = 'sports', banned = false },
    ['tigon'] = { name = 'tigon', maker = 'Lampadati', price = 400000, trunk = 20, glove = 15, type = 'car', class = 'super', banned = false },
    ['warrener'] = { name = 'Warrener', maker = 'Vulcar', price = 90000, trunk = 40, glove = 15, type = 'car', class = 'sedans', banned = false },
    ['tampa2'] = { name = 'Tampa2', maker = 'Declasse', price = 200000, trunk = 20, glove = 15, type = 'car', class = 'sports', banned = false },
    ['slamvan'] = { name = 'Slamvan', maker = 'Vapid', price = 180000, trunk = 100, glove = 15, type = 'car', class = 'muscle', banned = false },
    ['buffalo3'] = { name = 'Buffalo3', maker = 'Bravado', price = 300000, trunk = 50, glove = 15, type = 'car', class = 'sports', banned = false },
    ['surge'] = { name = 'Surge', maker = 'Cheval', price = 110000, trunk = 60, glove = 15, type = 'car', class = 'sedans', banned = false },
    ['entityxf'] = { name = 'Entityxf', maker = 'överflöd', price = 460000, trunk = 20, glove = 15, type = 'car', class = 'super', banned = false },
    ['burrito'] = { name = 'Burrito', maker = 'Declasse', price = 500000, trunk = 120, glove = 15, type = 'car', class = 'vans', banned = false },
    ['dominator2'] = { name = 'Dominator2', maker = 'Vapid', price = 230000, trunk = 50, glove = 15, type = 'car', class = 'muscle', banned = false },
    ['sanctus'] = { name = 'Sanctus', maker = 'Liberty city cycles', price = 1000000, trunk = 20, glove = 15, type = 'car', class = 'muscle', banned = false },
    ['baller4'] = { name = 'Baller4', maker = 'Gallivanter', price = 185000, trunk = 50, glove = 15, type = 'car', class = 'suvs', banned = false },
    ['bifta'] = { name = 'Bifta', maker = 'Bf', price = 190000, trunk = 20, glove = 15, type = 'car', class = 'offroad', banned = false },
    ['cheetah'] = { name = 'Cheetah', maker = 'Grotti', price = 425000, trunk = 20, glove = 15, type = 'car', class = 'super', banned = false },
    ['baller5'] = { name = 'Baller5', maker = 'Gallivanter', price = 270000, trunk = 50, glove = 15, type = 'car', class = 'suvs', banned = false },
    ['tornado2'] = { name = 'Tornado2', maker = 'Declasse', price = 160000, trunk = 60, glove = 15, type = 'car', class = 'sportsclassics', banned = false },
    ['comet6'] = { name = 'Comet6', maker = 'Pfister', price = 350000, trunk = 40, glove = 15, type = 'car', class = 'sports', banned = false },
    ['tornado'] = { name = 'Tornado', maker = 'Declasse', price = 150000, trunk = 70, glove = 15, type = 'car', class = 'sportsclassics', banned = false },
    ['burrito4'] = { name = 'Burrito4', maker = 'Declasse', price = 260000, trunk = 120, glove = 15, type = 'car', class = 'vans', banned = false },
    ['caracara2'] = { name = 'Caracara2', maker = 'Vapid', price = 670000, trunk = 200, glove = 15, type = 'car', class = 'offroad', banned = false },
    ['voltic'] = { name = 'Voltic', maker = 'Coil', price = 300000, trunk = 20, glove = 15, type = 'car', class = 'super', banned = false },
    ['gt500'] = { name = 'Gt500', maker = 'Grotti', price = 250000, trunk = 40, glove = 15, type = 'car', class = 'sportsclassics', banned = false },
    ['turismo2'] = { name = 'Turismo2', maker = 'Grotti', price = 250000, trunk = 30, glove = 15, type = 'car', class = 'sportsclassics', banned = false },
    ['sandking2'] = { name = 'Sandking2', maker = 'Vapid', price = 350000, trunk = 200, glove = 15, type = 'car', class = 'offroad', banned = false },
    ['ninef2'] = { name = 'Ninef2', maker = 'Obey', price = 290000, trunk = 40, glove = 15, type = 'car', class = 'sports', banned = false },
    ['coquette2'] = { name = 'Coquette2', maker = 'Invetero', price = 285000, trunk = 40, glove = 15, type = 'car', class = 'sportsclassics', banned = false },
    ['rancherxl'] = { name = 'Rancherxl', maker = 'Declasse', price = 220000, trunk = 70, glove = 15, type = 'car', class = 'offroad', banned = false },
    ['feltzer2'] = { name = 'Feltzer2', maker = 'Benefactor', price = 255000, trunk = 40, glove = 15, type = 'car', class = 'sports', banned = false },
    ['issi2'] = { name = 'Issi2', maker = 'Weeny', price = 75000, trunk = 20, glove = 15, type = 'car', class = 'compacts', banned = false },
    ['tampa3'] = { name = 'tampa3', maker = 'Declasse', price = 110000, trunk = 50, glove = 15, type = 'car', class = 'muscle', banned = false },
    ['openwheel2'] = { name = 'openwheel2', maker = 'Declasse Dinka', price = 400000, trunk = 0, glove = 0, type = 'car', class = 'Sports', banned = false },
    ['rt3000'] = { name = 'rt3000', maker = 'Dinka', price = 400000, trunk = 30, glove = 15, type = 'car', class = 'Sports', banned = false },
    ['euros'] = { name = 'euros', maker = 'Annis', price = 400000, trunk = 30, glove = 15, type = 'car', class = 'Sports', banned = false },
    ['utillitruck3'] = { name = 'Utillitruck3', maker = 'Vapid', price = 180000, trunk = 120, glove = 15, type = 'car', class = 'utility', banned = true },
    ['seven70'] = { name = 'Seven70', maker = 'Dewbauchee', price = 370000, trunk = 20, glove = 15, type = 'car', class = 'sports', banned = false },
    ['nero'] = { name = 'Nero', maker = 'Truffade', price = 450000, trunk = 20, glove = 15, type = 'car', class = 'super', banned = false },
    ['tornado6'] = { name = 'Tornado6', maker = 'Declasse', price = 250000, trunk = 50, glove = 15, type = 'car', class = 'sportsclassics', banned = false },
    ['taipan'] = { name = 'Taipan', maker = 'Cheval', price = 400000, trunk = 20, glove = 15, type = 'car', class = 'super', banned = false },
    ['mesa'] = { name = 'Mesa', maker = 'Canis', price = 90000, trunk = 50, glove = 15, type = 'car', class = 'suvs', banned = false },
    ['specter2'] = { name = 'Specter2', maker = 'Dewbauchee', price = 355000, trunk = 20, glove = 15, type = 'car', class = 'sports', banned = false },
    ['xa21'] = { name = 'Xa21', maker = 'Ocelot', price = 500000, trunk = 20, glove = 15, type = 'car', class = 'super', banned = false },
    ['issi3'] = { name = 'Issi3', maker = 'Weeny', price = 190000, trunk = 20, glove = 15, type = 'car', class = 'compacts', banned = false },
    ['stretch'] = { name = 'Stretch', maker = 'Dundreary', price = 1000000, trunk = 60, glove = 15, type = 'car', class = 'sedans', banned = false },
    ['vamos'] = { name = 'Vamos', maker = 'Declasse', price = 185000, trunk = 60, glove = 15, type = 'car', class = 'muscle', banned = false },
    ['benson'] = { name = 'Benson', maker = 'Vapid', price = 1000000, trunk = 1000, glove = 15, type = 'car', class = 'commercial', banned = false },
    ['neon'] = { name = 'Neon', maker = 'Pfister', price = 370000, trunk = 30, glove = 15, type = 'car', class = 'sports', banned = false },
    ['freecrawler'] = { name = 'Freecrawler', maker = 'Canis', price = 350000, trunk = 50, glove = 15, type = 'car', class = 'offroad', banned = false },
    ['rentalbus'] = { name = 'Ônibus Escolinha', maker = 'Brute', price = 0, trunk = 100, glove = 15, type = 'car', class = 'service', banned = false },
    ['tezeract'] = { name = 'Tezeract', maker = 'Pegassi', price = 920000, trunk = 20, glove = 15, type = 'car', class = 'super', banned = false },
    ['fq2'] = { name = 'Fq2', maker = 'Fathom', price = 110000, trunk = 50, glove = 15, type = 'car', class = 'suvs', banned = false },
    ['rebel2'] = { name = 'Rebel2', maker = 'Karin', price = 250000, trunk = 100, glove = 15, type = 'car', class = 'offroad', banned = false },
    ['specter'] = { name = 'Specter', maker = 'Dewbauchee', price = 320000, trunk = 20, glove = 15, type = 'car', class = 'sports', banned = false },
    ['asterope'] = { name = 'Asterope', maker = 'Karin', price = 65000, trunk = 30, glove = 15, type = 'car', class = 'sedans', banned = false },
    ['landstalker2'] = { name = 'Landstalker2', maker = 'Dundreary', price = 450000, trunk = 50, glove = 15, type = 'car', class = 'suvs', banned = false },
    ['toros'] = { name = 'Toros', maker = 'Pegassi', price = 350000, trunk = 50, glove = 15, type = 'car', class = 'suvs', banned = false },
    ['calico'] = { name = 'calico', maker = 'Karin', price = 400000, trunk = 30, glove = 15, type = 'car', class = 'Sports', banned = false },
    ['serrano'] = { name = 'Serrano', maker = 'Benefactor', price = 150000, trunk = 50, glove = 15, type = 'car', class = 'suvs', banned = false },
    ['paradise'] = { name = 'Paradise', maker = 'Bravado', price = 260000, trunk = 120, glove = 15, type = 'car', class = 'vans', banned = false },
    ['penumbra2'] = { name = 'penumbra2', maker = 'Maibatsu', price = 400000, trunk = 30, glove = 15, type = 'car', class = 'Sports', banned = false },
    ['jackal'] = { name = 'Jackal', maker = 'Ocelot', price = 60000, trunk = 50, glove = 15, type = 'car', class = 'coupes', banned = false },
    ['elegy2'] = { name = 'Elegy2', maker = 'Annis', price = 355000, trunk = 30, glove = 15, type = 'car', class = 'sports', banned = false },
    ['squaddie'] = { name = 'squaddie', maker = 'Mammoth', price = 400000, trunk = 30, glove = 15, type = 'car', class = 'suvs', banned = false },
    ['stanier'] = { name = 'Stanier', maker = 'Vapid', price = 15000, trunk = 60, glove = 15, type = 'car', class = 'sedans', banned = false },
    ['tyrus'] = { name = 'Tyrus', maker = 'Progen', price = 400000, trunk = 20, glove = 15, type = 'car', class = 'super', banned = false },
    ------------------------------------------------------------------------------------------------------------------------
    -- MOTOS
    ------------------------------------------------------------------------------------------------------------------------
    ['shotaro'] = { name = 'Shotaro', maker = 'Nagasaki', price = 1000000, trunk = 20, glove = 15, type = 'motocycle', class = 'motocycle', banned = false },
    ['cliffhanger'] = { name = 'Cliffhanger', maker = 'WMC', price = 310000, trunk = 20, glove = 15, type = 'motocycle', class = 'motocycle', banned = false },
    ['bati'] = { name = 'Bati', maker = 'Pegassi', price = 370000, trunk = 20, glove = 15, type = 'motocycle', class = 'motocycle', banned = false },
    ['double'] = { name = 'Double', maker = 'Dinka', price = 350000, trunk = 20, glove = 15, type = 'motocycle', class = 'motocycle', banned = false },
    ['innovation'] = { name = 'Innovation', maker = 'Liberty city cycles', price = 250000, trunk = 20, glove = 15, type = 'motocycle', class = 'motocycle', banned = false },
    ['bati2'] = { name = 'Bati2', maker = 'Pegassi', price = 300000, trunk = 20, glove = 15, type = 'motocycle', class = 'motocycle', banned = false },
    ['ruffian'] = { name = 'Ruffian', maker = 'Pegassi', price = 345000, trunk = 20, glove = 15, type = 'motocycle', class = 'motocycle', banned = false },
    ['carbonrs'] = { name = 'Carbonrs', maker = 'Nagasaki', price = 370000, trunk = 20, glove = 15, type = 'motocycle', class = 'motocycle', banned = false },
    ['vindicator'] = { name = 'Vindicator', maker = 'Dinka', price = 340000, trunk = 20, glove = 15, type = 'motocycle', class = 'motocycle', banned = false },
    ['avarus'] = { name = 'Avarus', maker = 'Liberty city cycles', price = 200000, trunk = 20, glove = 15, type = 'motocycle', class = 'motocycle', banned = false },
    ['blazer4'] = { name = 'Blazer4', maker = 'Nagasaki', price = 370000, trunk = 20, glove = 15, type = 'motocycle', class = 'offroad', banned = true },
    ['oppressor'] = { name = 'oppressor', maker = 'Pegassi', price = 300000, trunk = 0, glove = 0, type = 'motocycle', class = 'motocycle', banned = false },
    ['akuma'] = { name = 'Akuma', maker = 'Dinka', price = 850000, trunk = 20, glove = 15, type = 'motocycle', class = 'motocycle', banned = false },
    ['oppressor2'] = { name = 'oppressor2', maker = 'Pegassi', price = 300000, trunk = 0, glove = 0, type = 'motocycle', class = 'motocycle', banned = false },
    ['blazer'] = { name = 'Blazer', maker = 'Nagasaki', price = 230000, trunk = 20, glove = 15, type = 'motocycle', class = 'offroad', banned = true },
    ['lazer'] = { name = 'Blazer', maker = 'Nagasaki', price = 230000, trunk = 20, glove = 15, type = 'motocycle', class = 'offroad', banned = false },
    ['bagger'] = { name = 'Bagger', maker = 'WMC', price = 300000, trunk = 40, glove = 15, type = 'motocycle', class = 'motocycle', banned = false },
    ['daemon2'] = { name = 'Daemon2', maker = 'WMC', price = 150000, trunk = 20, glove = 15, type = 'motocycle', class = 'motocycle', banned = false },
    ['powersurge'] = { name = 'powersurge', maker = 'WMC', price = 300000, trunk = 15, glove = 15, type = 'motocycle', class = 'motocycle', banned = false },
    ['vader'] = { name = 'Vader', maker = 'Shitzu', price = 220000, trunk = 20, glove = 15, type = 'motocycle', class = 'motocycle', banned = false },
    ['esskey'] = { name = 'Esskey', maker = 'Pegassi', price = 50000, trunk = 20, glove = 15, type = 'motocycle', class = 'motocycle', banned = false },
    ['defiler'] = { name = 'Defiler', maker = 'Shitzu', price = 460000, trunk = 20, glove = 15, type = 'motocycle', class = 'motocycle', banned = false },
    ['diablous'] = { name = 'Diablous', maker = 'WMC', price = 430000, trunk = 20, glove = 15, type = 'motocycle', class = 'motocycle', banned = false },
    ['sanchez2'] = { name = 'Sanchez2', maker = 'Maibatsu', price = 125000, trunk = 20, glove = 15, type = 'motocycle', class = 'motocycle', banned = false },
    ['wolfsbane'] = { name = 'Wolfsbane', maker = 'WMC', price = 290000, trunk = 20, glove = 15, type = 'motocycle', class = 'motocycle', banned = false },
    ['lectro'] = { name = 'Lectro', maker = 'Principe', price = 380000, trunk = 20, glove = 15, type = 'motocycle', class = 'motocycle', banned = false },
    ['faggio3'] = { name = 'Faggio3', maker = 'Pegassi', price = 7500, trunk = 30, glove = 15, type = 'motocycle', class = 'motocycle', banned = false },
    ['manchez3'] = { name = 'manchez3', maker = 'Maibatsu', price = 300000, trunk = 15, glove = 0, type = 'motocycle', class = 'motocycle', banned = false },
    ['manchez2'] = { name = 'manchez2', maker = 'Maibatsu', price = 300000, trunk = 20, glove = 15, type = 'motocycle', class = 'motocycle', banned = false },
    ['sovereign'] = { name = 'Sovereign', maker = 'WMC', price = 285000, trunk = 50, glove = 15, type = 'motocycle', class = 'motocycle', banned = false },
    ['hexer'] = { name = 'Hexer', maker = 'Liberty city cycles', price = 250000, trunk = 20, glove = 15, type = 'motocycle', class = 'motocycle', banned = false },
    ['enduro'] = { name = 'Enduro', maker = 'Dinka', price = 50000, trunk = 20, glove = 15, type = 'motocycle', class = 'motocycle', banned = false },
    ['diablous2'] = { name = 'Diablous2', maker = 'WMC', price = 460000, trunk = 20, glove = 15, type = 'motocycle', class = 'motocycle', banned = false },
    ['rrocket'] = { name = 'rrocket', maker = 'WMC', price = 300000, trunk = 0, glove = 0, type = 'motocycle', class = 'motocycle', banned = false },
    ['nemesis'] = { name = 'Nemesis', maker = 'Principe', price = 345000, trunk = 20, glove = 15, type = 'motocycle', class = 'motocycle', banned = false },
    ['manchez'] = { name = 'Manchez', maker = 'Maibatsu', price = 355000, trunk = 20, glove = 15, type = 'motocycle', class = 'motocycle', banned = false },
    ['fcr'] = { name = 'Fcr', maker = 'Pegassi', price = 390000, trunk = 20, glove = 15, type = 'motocycle', class = 'motocycle', banned = false },
    ['hakuchou'] = { name = 'Hakuchou', maker = 'Shitzu', price = 380000, trunk = 20, glove = 15, type = 'motocycle', class = 'motocycle', banned = false },
    ['bf400'] = { name = 'Bf400', maker = 'Nagasaki', price = 150000, trunk = 20, glove = 15, type = 'motocycle', class = 'motocycle', banned = false },
    ['faggio'] = { name = 'Faggio', maker = 'Pegassi', price = 5000, trunk = 30, glove = 15, type = 'motocycle', class = 'motocycle', banned = false },
    ['faggio2'] = { name = 'Faggio2', maker = 'Pegassi', price = 5000, trunk = 30, glove = 15, type = 'motocycle', class = 'motocycle', banned = false },
    ['thrust'] = { name = 'Thrust', maker = 'Dinka', price = 375000, trunk = 20, glove = 15, type = 'motocycle', class = 'motocycle', banned = false },
    ['chimera'] = { name = 'Chimera', maker = 'Nagasaki', price = 345000, trunk = 20, glove = 15, type = 'motocycle', class = 'motocycle', banned = false },
    ['ratbike'] = { name = 'Ratbike', maker = 'WMC', price = 230000, trunk = 20, glove = 15, type = 'motocycle', class = 'motocycle', banned = false },
    ['gargoyle'] = { name = 'Gargoyle', maker = 'WMC', price = 345000, trunk = 20, glove = 15, type = 'motocycle', class = 'motocycle', banned = false },
    ['zombieb'] = { name = 'Zombieb', maker = 'Steel horse', price = 300000, trunk = 20, glove = 15, type = 'motocycle', class = 'motocycle', banned = false },
    ['stryder'] = { name = 'stryder', maker = 'Nagasaki', price = 300000, trunk = 15, glove = 0, type = 'motocycle', class = 'motocycle', banned = false },
    ['zombiea'] = { name = 'Zombiea', maker = 'WMC', price = 290000, trunk = 20, glove = 15, type = 'motocycle', class = 'motocycle', banned = false },
    ['hakuchou2'] = { name = 'Hakuchou2', maker = 'Shitzu', price = 550000, trunk = 20, glove = 15, type = 'motocycle', class = 'motocycle', banned = false },
    ['fcr2'] = { name = 'Fcr2', maker = 'Pegassi', price = 390000, trunk = 20, glove = 15, type = 'motocycle', class = 'motocycle', banned = false },
    ['pcj'] = { name = 'Pcj', maker = 'Shitzu', price = 50000, trunk = 20, glove = 15, type = 'motocycle', class = 'motocycle', banned = false },
    ['nightblade'] = { name = 'Nightblade', maker = 'Liberty chop shop', price = 350000, trunk = 20, glove = 15, type = 'motocycle', class = 'motocycle', banned = false },
    ['sanchez'] = { name = 'Sanchez', maker = 'Maibatsu', price = 185000, trunk = 20, glove = 15, type = 'motocycle', class = 'motocycle', banned = false },
    ['vortex'] = { name = 'Vortex', maker = 'Pegassi', price = 375000, trunk = 20, glove = 15, type = 'motocycle', class = 'motocycle', banned = false },
    ['deathbike2'] = { name = 'Death Bike', maker = 'WMC', price = 1000000, trunk = 0, glove = 15, type = 'motocycle', class = 'motocycle', banned = false },
    ------------------------------------------------------------------------------------------------------------------------
    -- PLANES
    ------------------------------------------------------------------------------------------------------------------------
    ['maverick'] = { name = 'Maverick', maker = 'Western company', price = 100000, trunk = 1000, glove = 15, type = 'helicopter', class = 'helicopter', banned = true },
    ['swift2'] = { name = 'Swift 2', maker = 'Buckingham', price = 0, trunk = 1000, glove = 15, type = 'helicopter', class = 'helicopter', banned = false },
    ['swift'] = { name = 'Swift', maker = 'Buckingham', price = 0, trunk = 1000, glove = 15, type = 'helicopter', class = 'helicopter', banned = false },
    ['frogger'] = { name = 'Frogger', maker = 'Maibatsu', price = 1000000, trunk = 0, glove = 15, type = 'helicopter', class = 'helicopters', banned = true },
    ['supervolito'] = { name = 'Supervolito', maker = 'Buckingham', price = 1000, trunk = 1000, glove = 15, type = 'helicopter', class = 'helicopters', banned = false },
    ['cargobob'] = { name = 'CSC Cargobob', maker = 'Western company', price = 1000000, trunk = 1000, glove = 15, type = 'helicopter', class = 'helicopters', banned = false },
    ['buzzard2'] = { name = 'Buzzard 2', maker = 'Nagasaki', price = 1000000, trunk = 1000, glove = 15, type = 'helicopter', class = 'helicopters', banned = false },
    ['cargobob2'] = { name = 'Cargo Bob', maker = 'Western company', price = 1000000, trunk = 1000, glove = 15, type = 'helicopter', class = 'helicopters', banned = false },
    ------------------------------------------------------------------------------------------------------------------------
    -- WORK
------------------------------------------------------------------------------------------------------------------------
    ['flatbed3'] = { name = 'Flatbed 3', maker = 'quantum', price = 1000, trunk = 0, glove = 15, type = 'work', class = 'commercial', banned = true },
    ['raptor150'] = { name = 'Raptor', maker = 'Ford', price = 1000, trunk = 0, glove = 15, type = 'work', class = 'commercial', banned = true },
    ['avisa'] = { name = 'avisa', maker = 'Kraken', price = 1000, trunk = 0, glove = 15, type = 'work', class = 'boats', banned = true },
    ['toro'] = { name = 'Toro', maker = 'Lampadati', price = 1000, trunk = 0, glove = 15, type = 'work', class = 'boats', banned = true },
    ['jetmax'] = { name = 'Jetmax', maker = 'Grotti', price = 1000, trunk = 0, glove = 15, type = 'work', class = 'boats', banned = true },
    ['vestra'] = { name = 'Vestra', maker = 'Buckingham', price = 1000, trunk = 0, glove = 15, type = 'work', class = 'planes', banned = true },
    ['cog55'] = { name = 'Cog55', maker = 'Enus', price = 200000, trunk = 50, glove = 15, type = 'work', class = 'sedans', banned = false },
    ['youga2'] = { name = 'Youga2', maker = 'Bravado', price = 1000, trunk = 80, glove = 15, type = 'work', class = 'vans', banned = false },
    ['coach'] = { name = 'Coach', maker = 'Brute', price = 1000, trunk = 0, glove = 15, type = 'work', class = 'service', banned = true },
    ['riot'] = { name = 'Blindado', maker = 'Brute', price = 1000, trunk = 0, glove = 15, type = 'work', class = 'emergency', banned = true },
    ['mule'] = { name = 'Mule', maker = 'Maibatsu', price = 500000, trunk = 0, glove = 15, type = 'work', class = 'commercial', banned = true },
    ['flatbed'] = { name = 'Reboque', maker = 'MTL', price = 1000, trunk = 0, glove = 15, type = 'work', class = 'industrial', banned = true },
    ['superd'] = { name = 'Superd', maker = 'Enus', price = 200000, trunk = 50, glove = 15, type = 'work', class = 'sedans', banned = false },
    ['ratloader'] = { name = 'Caminhão', maker = 'Bravado', price = 80000, trunk = 80, glove = 15, type = 'work', class = 'muscle', banned = true },
    ['towtruck2'] = { name = 'Towtruck2', maker = 'Vapid', price = 1000, trunk = 0, glove = 15, type = 'work', class = 'utility', banned = true },
    ['daemon'] = { name = 'Daemon', maker = 'WMC', price = 75000, trunk = 20, glove = 15, type = 'work', class = 'motocycle', banned = false },
    ['miljet'] = { name = 'Miljet', maker = 'Western company', price = 1000, trunk = 0, glove = 15, type = 'work', class = 'planes', banned = true },
    ['bmx'] = { name = 'Bmx', maker = 'Bmx', price = 1, trunk = 0, glove = 15, type = 'work', class = 'cycles', banned = true },
    ['ambulance'] = { name = 'Ambulância', maker = 'Brute', price = 1000, trunk = 0, glove = 15, type = 'work', class = 'emergency', banned = true },
    ['primo2'] = { name = 'Primo2', maker = 'Albany', price = 100000, trunk = 60, glove = 15, type = 'work', class = 'sedans', banned = false },
    ['boxville'] = { name = 'BoxVille', maker = 'Brute', price = 1000, trunk = 70, glove = 15, type = 'work', class = 'vans', banned = true },
    ['ratloader2'] = { name = 'Ratloader2', maker = 'Bravado', price = 1000, trunk = 70, glove = 15, type = 'work', class = 'muscle', banned = false },
    ['felon2'] = { name = 'Felon2', maker = 'Lampadati', price = 1000, trunk = 40, glove = 15, type = 'work', class = 'coupes', banned = false },
    ['tribike3'] = { name = 'Tribike3', maker = 'Bmx', price = 1000, trunk = 0, glove = 15, type = 'work', class = 'cycles', banned = true },
    ['phantom'] = { name = 'Phantom', maker = 'Jobuilt', price = 1000, trunk = 0, glove = 15, type = 'work', class = 'commercial', banned = true },
    ['cruiser'] = { name = 'Cruiser', maker = 'Bmx', price = 1000, trunk = 0, glove = 15, type = 'work', class = 'cycles', banned = true },
    ['polmav'] = { name = 'Polmav', maker = 'Buckingham', price = 0, trunk = 0, glove = 15, type = 'work', class = 'emergency', banned = true },
    ['speeder'] = { name = 'Speeder', maker = 'Pegassi', price = 1000, trunk = 0, glove = 15, type = 'work', class = 'boats', banned = true },
    ['supervolito2'] = { name = 'Supervolito2', maker = 'Buckingham', price = 1000, trunk = 0, glove = 15, type = 'work', class = 'helicopters', banned = true },
    ['btype'] = { name = 'Btype', maker = 'Albany', price = 200000, trunk = 40, glove = 15, type = 'work', class = 'sportsclassics', banned = false },
    ['boxville4'] = { name = 'BoxVille4', maker = 'Brute', price = 1000, trunk = 70, glove = 15, type = 'work', class = 'vans', banned = true },
    ['squalo'] = { name = 'Squalo', maker = 'Grotti', price = 1000, trunk = 0, glove = 15, type = 'work', class = 'boats', banned = true },
    ['speedo'] = { name = 'Speedo', maker = 'Vapid', price = 200000, trunk = 120, glove = 15, type = 'work', class = 'vans', banned = false },
    ['slamvan2'] = { name = 'Slamvan2', maker = 'Vapid', price = 200000, trunk = 100, glove = 15, type = 'work', class = 'muscle', banned = false },
    ['tornado5'] = { name = 'Tornado5', maker = 'Declasse', price = 200000, trunk = 60, glove = 15, type = 'work', class = 'sportsclassics', banned = false },
    ['gburrito'] = { name = 'GBurrito', maker = 'Declasse', price = 500000, trunk = 100, glove = 15, type = 'work', class = 'vans', banned = false },
    ['trailerlogs'] = { name = 'Woods', maker = 'Brute', price = 1000, trunk = 0, glove = 15, type = 'work', class = 'utility', banned = true },
    ['volatus'] = { name = 'Volatus', maker = 'Buckingham', price = 1000000, trunk = 1000, glove = 15, type = 'work', class = 'helicopters', banned = true },
    ['seashark3'] = { name = 'Seashark3', maker = 'Speedophile', price = 1000, trunk = 0, glove = 15, type = 'work', class = 'boats', banned = true },
    ['fbi2'] = { name = 'Granger FBI', maker = 'Declasse', price = 1000, trunk = 0, glove = 15, type = 'work', class = 'emergency', banned = true },
    ['marquis'] = { name = 'Marquis', maker = 'Dinka', price = 1000, trunk = 0, glove = 15, type = 'work', class = 'boats', banned = true },
    ['graintrailer'] = { name = 'GrainTrailer', maker = 'Brute', price = 1000, trunk = 500, glove = 15, type = 'work', class = 'utility', banned = false },
    ['tvtrailer'] = { name = 'Show', maker = 'Brute', price = 1000, trunk = 0, glove = 15, type = 'work', class = 'utility', banned = true },
    ['tanker2'] = { name = 'Gas', maker = 'Brute', price = 1000, trunk = 0, glove = 15, type = 'work', class = 'utility', banned = true },
    ['toro2'] = { name = 'Toro2', maker = 'Lampadati', price = 1000, trunk = 0, glove = 15, type = 'work', class = 'boats', banned = true },
    ['tiptruck'] = { name = 'Tiptruck', maker = 'Brute', price = 1000, trunk = 70, glove = 15, type = 'work', class = 'industrial', banned = false },
    ['trash2'] = { name = 'Caminhão Lixo', maker = 'Brute', price = 1000, trunk = 80, glove = 15, type = 'work', class = 'utility', banned = false },
    ['towtruck'] = { name = 'Towtruck', maker = 'Vapid', price = 1000, trunk = 0, glove = 15, type = 'work', class = 'utility', banned = true },
    ['rebel'] = { name = 'Rebel', maker = 'Karin', price = 1000, trunk = 80, glove = 15, type = 'work', class = 'offroad', banned = false },
    ['rubble'] = { name = 'Caminhão', maker = 'Jobuilt', price = 1000, trunk = 200, glove = 15, type = 'work', class = 'industrial', banned = false },
    ['caddy'] = { name = 'Caddy', maker = 'Work', price = 180000, trunk = 120, glove = 15, type = 'work', class = 'utility', banned = true },
    ['caddy2'] = { name = 'Caddy 2', maker = 'Work', price = 180000, trunk = 120, glove = 15, type = 'work', class = 'utility', banned = true },
    ['stafford'] = { name = 'Stafford', maker = 'Enus', price = 150000, trunk = 40, glove = 15, type = 'work', class = 'sedans', banned = false },
    ['dinghy'] = { name = 'Dinghy', maker = 'Nagasaki', price = 1000, trunk = 0, glove = 15, type = 'work', class = 'boats', banned = true },
    ['mammatus'] = { name = 'Mammatus', maker = 'Jobuilt', price = 1000, trunk = 0, glove = 15, type = 'work', class = 'planes', banned = true },
    ['armytanker'] = { name = 'Diesel', maker = 'Brute', price = 1000, trunk = 0, glove = 15, type = 'work', class = 'utility', banned = true },
    ['police4'] = { name = 'Cruiser FBI', maker = 'Vapid', price = 1000, trunk = 0, glove = 15, type = 'work', class = 'emergency', banned = true },
    ['fbi'] = { name = 'Buffalo FBI', maker = 'Declasse', price = 1000, trunk = 0, glove = 15, type = 'work', class = 'emergency', banned = true },
    ['suntrap'] = { name = 'Suntrap', maker = 'Shitzu', price = 1000, trunk = 0, glove = 15, type = 'work', class = 'boats', banned = true },
    ['bus'] = { name = 'Ônibus', maker = 'Brute', price = 1000, trunk = 0, glove = 15, type = 'work', class = 'service', banned = true },
    ['faction2'] = { name = 'Faction2', maker = 'Willard', price = 200000, trunk = 40, glove = 15, type = 'work', class = 'muscle', banned = false },
    ['cuban800'] = { name = 'Cuban800', maker = 'Western company', price = 1000, trunk = 0, glove = 15, type = 'work', class = 'planes', banned = true },
    ['velum2'] = { name = 'Velum2', maker = 'Jobuilt', price = 1000, trunk = 0, glove = 15, type = 'work', class = 'planes', banned = true },
    ['boxville2'] = { name = 'BoxVille2', maker = 'Brute', price = 1000, trunk = 70, glove = 15, type = 'work', class = 'vans', banned = true },
    ['seashark2'] = { name = 'seashark2', maker = 'Kraken', price = 1000, trunk = 0, glove = 15, type = 'work', class = 'Speedophile', banned = true },
    ['tribike'] = { name = 'Tribike', maker = 'Bmx', price = 1000, trunk = 0, glove = 15, type = 'work', class = 'cycles', banned = true },
    ['tropic2'] = { name = 'Tropic2', maker = 'Grotti', price = 1000, trunk = 0, glove = 15, type = 'work', class = 'boats', banned = true },
    ['bison2'] = { name = 'Bison2', maker = 'Bravado', price = 0, trunk = 0, glove = 15, type = 'work', class = 'vans', banned = true },
    ['luxor2'] = { name = 'Luxor Dourado', maker = 'Western company', price = 1000, trunk = 0, glove = 15, type = 'work', class = 'planes', banned = true },
    ['tropic'] = { name = 'Tropic', maker = 'Grotti', price = 1000, trunk = 0, glove = 15, type = 'work', class = 'boats', banned = true },
    ['packer'] = { name = 'Packer', maker = 'MTL', price = 1000, trunk = 0, glove = 15, type = 'work', class = 'commercial', banned = true },
    ['seasparrow'] = { name = 'Paramédico Helicóptero Água', maker = 'Maibatsu', price = 1000, trunk = 0, glove = 15, type = 'work', class = 'helicopters', banned = true },
    ['taxi'] = { name = 'Taxi', maker = 'Vapid', price = 1000, trunk = 0, glove = 15, type = 'work', class = 'service', banned = true },
    ['tribike2'] = { name = 'Tribike2', maker = 'Bmx', price = 1000, trunk = 0, glove = 15, type = 'work', class = 'cycles', banned = true },
    ['tr4'] = { name = 'Carga de Carros', maker = 'Brute', price = 1000, trunk = 0, glove = 15, type = 'work', class = 'utility', banned = true },
    ['tractor2'] = { name = 'Tractor2', maker = 'Stanley', price = 1000, trunk = 80, glove = 15, type = 'work', class = 'utility', banned = false },
    ['chino2'] = { name = 'Chino2', maker = 'Vapid', price = 100000, trunk = 60, glove = 15, type = 'work', class = 'muscle', banned = false },
    ['policeb'] = { name = 'Harley Davidson', maker = 'WMC', price = 1000, trunk = 0, glove = 15, type = 'work', class = 'emergency', banned = true },
    ['pbus'] = { name = 'PBus', maker = 'Brute', price = 1000, trunk = 0, glove = 15, type = 'work', class = 'emergency', banned = true },
    ['bison3'] = { name = 'Bison3', maker = 'Bravado', price = 0, trunk = 0, glove = 15, type = 'work', class = 'vans', banned = true },
    ['utillitruck'] = { name = 'Utillitruck', maker = 'Vapid', price = 180000, trunk = 120, glove = 15, type = 'work', class = 'utility', banned = true },
    ['scorcher'] = { name = 'Scorcher', maker = 'Bmx', price = 1000, trunk = 0, glove = 15, type = 'work', class = 'cycles', banned = true },
    ['350z'] = { name = 'Zenthor', maker = 'Tensa', price = 20000, trunk = 20, glove = 5, type = 'car', class = 'sport', banned = false },
['acuransx'] = { name = 'Nexus X', maker = 'Asura', price = 25000, trunk = 15, glove = 7, type = 'car', class = 'sport', banned = false },
['astonmartindbs'] = { name = 'Cronos DBS', maker = 'Gallant', price = 50000, trunk = 25, glove = 10, type = 'car', class = 'luxury', banned = false },
['audir8'] = { name = 'Aspira R8', maker = 'Gallant', price = 70000, trunk = 30, glove = 8, type = 'car', class = 'super', banned = false },
['audirs6'] = { name = 'Aspira RS6', maker = 'Gallant', price = 40000, trunk = 35, glove = 12, type = 'car', class = 'sport', banned = false },
['bloodline'] = { name = 'Crimson', maker = 'Phantom', price = 30000, trunk = 10, glove = 8, type = 'car', class = 'muscle', banned = false },
['bmwi8'] = { name = 'Inova I8', maker = 'Bavura', price = 80000, trunk = 15, glove = 6, type = 'car', class = 'super', banned = false },
['bmwm1wb'] = { name = 'Mach WB1', maker = 'Bavura', price = 35000, trunk = 20, glove = 9, type = 'car', class = 'sport', banned = false },
['bmwm4gts'] = { name = 'Mach G4', maker = 'Bavura', price = 50000, trunk = 25, glove = 10, type = 'car', class = 'luxury', banned = false },
['bmwm5e34'] = { name = 'Mach E5', maker = 'Bavura', price = 30000, trunk = 20, glove = 8, type = 'car', class = 'sedan', banned = false },
['caminhaozinho'] = { name = 'Cargovan', maker = 'Utility Co.', price = 15000, trunk = 100, glove = 2, type = 'car', class = 'utility', banned = false },
['civictyper'] = { name = 'Comet Type-R', maker = 'Vortex', price = 20000, trunk = 15, glove = 7, type = 'car', class = 'sport', banned = false },
['dodgecharger1970'] = { name = 'Dominion 70', maker = 'Titan', price = 35000, trunk = 25, glove = 10, type = 'car', class = 'muscle', banned = false },
['dodgechargerrt69'] = { name = 'Dominion RT69', maker = 'Titan', price = 38000, trunk = 20, glove = 8, type = 'car', class = 'muscle', banned = false },
['dodgechargersrt'] = { name = 'Dominion SRT', maker = 'Titan', price = 40000, trunk = 30, glove = 12, type = 'car', class = 'muscle', banned = false },
['dodgeramtrx'] = { name = 'Raider TRX', maker = 'Titan', price = 45000, trunk = 50, glove = 5, type = 'car', class = 'offroad', banned = false },
['f8t'] = { name = 'Falcon T8', maker = 'Scorpius', price = 70000, trunk = 15, glove = 6, type = 'car', class = 'super', banned = false },
['ferrari812'] = { name = 'Tempest 812', maker = 'Scorpius', price = 90000, trunk = 10, glove = 8, type = 'car', class = 'super', banned = false },
['ferrarif12'] = { name = 'Tempest F12', maker = 'Scorpius', price = 85000, trunk = 12, glove = 7, type = 'car', class = 'super', banned = false },
['ferrarif40'] = { name = 'Tempest F40', maker = 'Scorpius', price = 95000, trunk = 8, glove = 5, type = 'car', class = 'super', banned = false },
['ferrariitalia'] = { name = 'Tempest Italia', maker = 'Scorpius', price = 80000, trunk = 15, glove = 9, type = 'car', class = 'super', banned = false },
['fordbronco'] = { name = 'Buffalo', maker = 'Pioneer', price = 30000, trunk = 40, glove = 6, type = 'car', class = 'offroad', banned = false },
['fordmustang'] = { name = 'Mustang', maker = 'Pioneer', price = 40000, trunk = 25, glove = 10, type = 'car', class = 'muscle', banned = false },
['golf75r'] = { name = 'Bolt 75R', maker = 'Autonova', price = 25000, trunk = 20, glove = 8, type = 'car', class = 'sport', banned = false },
['golfgti'] = { name = 'Bolt GTI', maker = 'Autonova', price = 23000, trunk = 18, glove = 7, type = 'car', class = 'sport', banned = false },
['golfmk7'] = { name = 'Bolt MK7', maker = 'Autonova', price = 24000, trunk = 20, glove = 9, type = 'car', class = 'sport', banned = false },
['jeepcherokee'] = { name = 'Trailblazer', maker = 'Trekker', price = 45000, trunk = 50, glove = 6, type = 'car', class = 'offroad', banned = false },
['lamborghinihuracan'] = { name = 'Vulcan H', maker = 'Scorpius', price = 100000, trunk = 15, glove = 6, type = 'car', class = 'super', banned = false },
['lamborghinihuracanlw'] = { name = 'Vulcan HLW', maker = 'Scorpius', price = 110000, trunk = 15, glove = 5, type = 'car', class = 'super', banned = false },
['lancerevolution9'] = { name = 'Striker Evo 9', maker = 'Blaze', price = 35000, trunk = 20, glove = 9, type = 'car', class = 'sport', banned = false },
['lancerevolutionx'] = { name = 'Striker Evo X', maker = 'Blaze', price = 40000, trunk = 20, glove = 8, type = 'car', class = 'sport', banned = false },
['mazdarx7'] = { name = 'Vortex RX7', maker = 'Asura', price = 30000, trunk = 15, glove = 6, type = 'car', class = 'sport', banned = false },
['mazdarx72'] = { name = 'Vortex RX72', maker = 'Asura', price = 32000, trunk = 15, glove = 5, type = 'car', class = 'sport', banned = false },
['mb608d'] = { name = 'Hauler 608D', maker = 'Titan', price = 15000, trunk = 80, glove = 5, type = 'car', class = 'utility', banned = false },
['mclarenp1'] = { name = 'Phantom P1', maker = 'Scorpius', price = 120000, trunk = 10, glove = 4, type = 'car', class = 'super', banned = false },
['mclarensenna'] = { name = 'Phantom Senna', maker = 'Scorpius', price = 130000, trunk = 8, glove = 5, type = 'car', class = 'super', banned = false },
['mercedesamg63'] = { name = 'Aspira AMG63', maker = 'Gallant', price = 60000, trunk = 40, glove = 8, type = 'car', class = 'luxury', banned = false },
['mercedesgt63'] = { name = 'Aspira GT63', maker = 'Gallant', price = 70000, trunk = 35, glove = 10, type = 'car', class = 'luxury', banned = false },
['mustangfast'] = { name = 'Pioneer Fastback', maker = 'Pioneer', price = 45000, trunk = 25, glove = 8, type = 'car', class = 'muscle', banned = false },
['nissangtr'] = { name = 'Tensa GT-R', maker = 'Tensa', price = 70000, trunk = 15, glove = 7, type = 'car', class = 'sport', banned = false },
['nissangtr2'] = { name = 'Tensa GT-R MK2', maker = 'Tensa', price = 75000, trunk = 15, glove = 6, type = 'car', class = 'sport', banned = false },
['nissangtr3'] = { name = 'Tensa GT-R MK3', maker = 'Tensa', price = 80000, trunk = 15, glove = 6, type = 'car', class = 'sport', banned = false },
['nissangtr50'] = { name = 'Tensa GT-R50', maker = 'Tensa', price = 100000, trunk = 10, glove = 5, type = 'car', class = 'super', banned = false },
['nissangtrnismo'] = { name = 'Tensa Nismo', maker = 'Tensa', price = 120000, trunk = 10, glove = 5, type = 'car', class = 'super', banned = false },
['panameramansory'] = { name = 'Velox Mansory', maker = 'Gallant', price = 90000, trunk = 40, glove = 6, type = 'car', class = 'luxury', banned = false },
['porsche718'] = { name = 'Velox 718', maker = 'Gallant', price = 60000, trunk = 20, glove = 7, type = 'car', class = 'sport', banned = false },
['porsche911'] = { name = 'Velox 911', maker = 'Gallant', price = 80000, trunk = 15, glove = 8, type = 'car', class = 'sport', banned = false },
['r1'] = { name = 'Roadmaster R1', maker = 'Nexus', price = 20000, trunk = 0, glove = 3, type = 'bike', class = 'motorcycle', banned = false },
['r6'] = { name = 'Roadmaster R6', maker = 'Nexus', price = 25000, trunk = 0, glove = 4, type = 'bike', class = 'motorcycle', banned = false },
['rs52018'] = { name = 'Bolt RS5', maker = 'Gallant', price = 50000, trunk = 25, glove = 8, type = 'car', class = 'luxury', banned = false },
['s1000rr'] = { name = 'Roadmaster S1000RR', maker = 'Nexus', price = 30000, trunk = 0, glove = 3, type = 'bike', class = 'motorcycle', banned = false },
['shelbygt500'] = { name = 'Titan GT500', maker = 'Titan', price = 70000, trunk = 25, glove = 10, type = 'car', class = 'muscle', banned = false },
['silverado1500'] = { name = 'Raider 1500', maker = 'Pioneer', price = 50000, trunk = 60, glove = 6, type = 'car', class = 'offroad', banned = false },
['skyliner34'] = { name = 'Skyhawk R34', maker = 'Tensa', price = 55000, trunk = 20, glove = 9, type = 'car', class = 'sport', banned = false },
['skyliner342'] = { name = 'Skyhawk R342', maker = 'Tensa', price = 60000, trunk = 18, glove = 8, type = 'car', class = 'sport', banned = false },
}






config.blips = {
    ['carOnly'] = {
        sprite = 357,
        color = 3,
        scale = 0.6,
    }
}

config.garages = {
    {
        coords = vector3(1206.712, -2288.149, -49.00439), 
        leave = vector3(-1605.587, -828.1846, 10.0542), 
        rule = 'carOnly',
        showBlip = true,
        points = {
            vector4(1219.503, -2286.369, -49.00439, 2.834646),
            vector4(1222.971, -2287.332, -49.00439, 2.834646),
            vector4(1227.93, -2286.488, -49.00439, 0)
        }
    },

    {
        coords = vector3(526.2593, -2608.642, -49.00439), 
        leave = vector3(35.67033, -903.2044, 30.20654),
        rule = 'carOnly',
        showBlip = true,
        points = {
            vector4(514.8923, -2613.283, -49.00439, 277.7953),
            vector4(514.444, -2621.024, -49.00439, 277.7953),
            vector4(514.0088, -2629.833, -49.00439, 280.6299)
        }
    },

    {
        coords = vector3(-1069.899, -62.80879, -94.59998), 
        leave = vector3(41.8022, 6451.213, 31.4198),
        rule = 'carOnly',
        showBlip = true,
        points = {
            vector4(-1065.64, -67.5033, -94.59998, 85.03937),
            vector4(-1066.101, -74.46593, -94.59998, 90.70866),
            vector4(-1079.644, -74.58461, -94.59998, 269.2914)
        }
    },

    {
        coords = vector3(173.0769, -1000.154, -99.01465), 
        leave = vector3(1410.989, 3620.664, 34.89087),
        rule = 'carOnly',
        showBlip = true,
        points = {
            vector4(173.0374, -1003.754, -99.01465, 172.9134)
        }
    },
    
    {
        coords = vector3(1,1,1), 
        rule = 'carOnly',
        leave = vector3(-1605.587, -828.1846, 10.0542), 
        permission = 'vippm.permissao',
        points = {
            vector4(-2282.176, 404.1758, 174.4579, 119.0551),
            vector4(-2284.22, 407.2088, 174.4579, 124.7244),
            vector4(-2286.725, 410.2154, 174.4579, 136.063),
        },
        vehicles = { 'wrbmwx6', 'ndagera', 'wrbmwx7' }
    },
    {
        coords = vector3(-2292.356, 420.1451, 174.5927), 
        rule = 'carOnly',
        permission = 'policia.permissao',
        points = {
            vector4(-2296.338, 415.7538, 174.4579, 161.5748),
            vector4(-2292.58, 414.4088, 174.4579, 150.2362),
            vector4(-2289.534, 412.2198, 174.4579, 144.5669),
        },
        vehicles = { 'skyliner342' }
    },
    {
        coords = vector3(-2267.776, 386.4396, 193.2117), 
        rule = 'heliOnly',
        marker = 'heli',
        permission = 'policia.permissao',
        points = {
            vector4(-2267.644, 395.0901, 193.1274, 68.03149)
        },
        vehicles = { 'bmheli' }
    },

    -- Works
    {
        coords = vector3(713.3143, -976.8132, 24.12378),
        rule = 'carOnly',
        points = {
            vector4(712.7077, -981.3758, 24.14062, 223.937),
            vector4(708.3824, -981.7319, 24.10693, 221.1024)
        },
        vehicles = {
            'bison3'
        }
    },
    {
        coords = vector3(1189.912, -3249.455, 6.060791),
        rule = 'carOnly',
        points = {
            vector4(1188.343, -3245.96, 6.0271, 87.87402),
            vector4(1188.079, -3242.651, 6.0271, 85.03937)
        },
        vehicles = {
            'boxville4'
        }
    },
    {
        coords = vector3(116.0176, 102.7516, 81.1604),
        rule = 'carOnly',
        points = {
            vector4(116.0176, 96.8044, 80.73926, 141.7323),
            vector4(112.3516, 98.18901, 80.58752, 164.4095)
        },
        vehicles = {
            'boxville2'
        }
    },
    {
        coords = vector3(1998.738, 3056.769, 47.03955),
        rule = 'carOnly',
        points = {
            vector4(2000.11, 3060.791, 47.03955, 223.937)
        },
        vehicles = {
            'boxville'
        }
    },
    {
        coords = vector3(916.2593, 3560.506, 33.79565),
        rule = 'carOnly',
        points = {
            vector4(923.7495, 3564.026, 33.79565, 172.9134)
        },
        vehicles = {
            'bison2'
        }
    },
    {
        coords = vector3(-333.244, -1518.25, 27.52747),
        rule = 'carOnly',
        points = {
            vector4(-329.2879, -1518.185, 27.52747, 175.748),
            vector4(-325.9648, -1518.488, 27.52747, 175.748)
        },
        vehicles = {
            'caddy'
        }
    },
    {
        coords = vector3(745.622, 136.2989, 80.16626),
        rule = 'carOnly',
        points = {
            vector4(749.2615, 129.4022, 78.93628, 235.2756)
        },
        vehicles = {
            'utillitruck'
        }
    },

    -- [PRISAO] --
    {
        coords = vector3(1852.365, 2601.706, 45.65784),
        marker = 'bike',
        points = {
            vector4(1854.105, 2607.046, 45.05127, 274.9606),
        },
        vehicles = { 'bmx' }
    },
    {
        coords = vector3(-779.8154, -1221.191, 15.54724),
        rule = 'heliOnly',
        marker = 'heli',
        permission = 'hospital.permissao',
        points = {
           vector4(-788.2154, -1229.143, 15.54724, 42.51968)
        },
        vehicles = { 'wrvolito' }
    },
}

config.rules = {
    ['carOnly'] = {
        ['show_classes'] = nil,
        ['hide_classes'] = { ['planes'] = true, ['helicopters'] = true, ['boats'] = true }
    },
    ['heliOnly'] = {
        ['show_classes'] = { ['helicopters'] = true },
        ['hide_classes'] = nil
    },
    ['planeOnly'] = {
        ['show_classes'] = { ['planes'] = true },
        ['hide_classes'] = nil
    },
    ['boatsOnly'] = {
        ['show_classes'] = { ['boats'] = true },
        ['hide_classes'] = nil
    },
}

config.hashes = {}

for vname, data in pairs(config.vehicles) do
	if (data.hash) then
		config.hashes[data.hash] = vname
	else		
		local model = GetHashKey(vname)
		config.vehicles[vname].hash = model
		config.hashes[model] = vname
	end
end